version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - user-service

  user-service:
    build: ./user
    container_name: user
    network_mode: host
    ports:
      - "5000:5000"
  
